### ISSUE TITLE
Please add a README

### ISSUE THREAD

**Issue by FascinatedBox** [drasticactions/miiversearchive#1]
How does this work, what options are there, where does it save to, etc?

**Comment by drasticactions** [comment]
I have, but some notes on this:

- This repo is intended for scratch work at the moment, trying to find good ways to parse the data.
- This program itself _probably_ won't be what's used to fully archive the site. My hope is that using the knowledge this program brings, I can port it over to a [Warrior](http://archiveteam.org/index.php?title=ArchiveTeam_Warrior) project. 
-But I also need to make sure their stuff can handle the way Miiverse is set up. The worse case is this will become a full blown crawler, and then I'll have to set up a way to have multiple machines crawl and save data.

So this is to show my work is open source, but I don't expect PRs or anything since there's not much you can do with this yet. I'll announce more as I go. Your best bet is to go to [Miiworse](http://chat.efnet.org:9090/?channels=%23miiworse) on the Archive Teams efnet IRC channel. I'll be hanging out there.
